### ISSUE TITLE
Build issue on Linux

### ISSUE THREAD

**Issue by keniwhat** [sushichop/Puppy#24]
Build error:
<unknown>:0: error: missing required module 'CPuppy'

**Comment by sushichop** [comment]
@keniwhat 
Thanks for reporting this.

Are you using `swift build` command and Linux with Swift Toolchain? See [Download Swift](https://swift.org/download/).
I basically use a docker container(Ubuntu 18.04 or 20.04 with Swift Toolchain) to check it, though.

Or if you use Swift version 5.3.x or before, try to use [Puppy 0.3.1](https://github.com/sushichop/Puppy/releases/tag/0.3.1).

Thanks.

**Comment by keniwhat** [comment]
Fixed in 0.3.1 for Linux Toolchain 5.3.3.

Thanks.

**Comment by sushichop** [comment]
Thanks for checking it. 
I'm closing this issue:)
