### ISSUE TITLE
Puppy tries to delete all files in directory

### ISSUE THREAD

**Issue by keniwhat** [sushichop/Puppy#27]
When using an existing directory for log files, Puppy will try to delete all files in the directory when rotating logs, not just the Puppy logs.
To solve this I put my logs into a specific directory.  This is fine, but generally people may want to put logs into a generic 'log' directory.

But .... puppy is great.  File rotation logging is why I use it.
Thanks.

**Comment by sushichop** [comment]
@keniwhat 

Thanks for your feedback.
Yes, it's correct. I'll consider a better solution in the future.

Thanks.

**Comment by sushichop** [comment]
Hi, all!
This issue fixed by #32.
At the same time, I added options of suffix extension types in `FileRotationLogger`.
See #32 and README for details.

Thanks.

**Comment by sushichop** [comment]
I have released Puppy@0.4.0 that fixes this issue.
Check [release note](https://github.com/sushichop/Puppy/releases/tag/0.4.0) and [README](https://github.com/sushichop/Puppy#readme) because some specifications of `FileLogger` and `FileRotationLogger` have been changed.

Thanks.

**Comment by sushichop** [comment]
I'm going to close this issue as I haven't heard from you in a while unfortunately.
This issue has already been fixed.

Try to use the latest version [Puppy 0.5.0](https://github.com/sushichop/Puppy/releases/tag/0.5.0). And Windows is now supported.

Thanks.
