### ISSUE TITLE
Empty permissions create on log rotation

### ISSUE THREAD

**Issue by keniwhat** [sushichop/Puppy#35]
On macOS (Big Sur) with Apple Silicon chipset (m1), when a log file is rotated, when the new empty log file is created, it is created with empty permissions (------------).  This causes the application to crash with an unexpected nil optional for the file handle (failed to open file for writing?).

NOTE: This looks like a macOS bug where the 'umask' is not taken into account, or is lost at the point of log rotation, because initially a file with proper permissions is created (if not, we could not get to the first point of log rotation).

NOTE: THIS ONLY HAPPENS ON APPLE SILICON.

Changing the openFile function as follows fixes the issue:

let successful = FileManager.default.createFile(atPath: fileURL.path, contents: nil, attributes: [FileAttributeKey.posixPermissions: 0o660])

Obviously a better solution would be to allow the attributes to be specified via some other means, eg: FileLoggerDelegate protocol.

Thanks.  Still a great framework :-)

**Comment by sushichop** [comment]
@keniwhat
Thanks for reporting this.
I have added an option to set file permissions in `FileLogger` and `FileRoationLogger`.
See #36  for details.

Thanks.

**Comment by sushichop** [comment]
I have released Puppy@0.4.0 that fixes this issue.
Check [release note](https://github.com/sushichop/Puppy/releases/tag/0.4.0) and [README](https://github.com/sushichop/Puppy#readme) because some specifications of `FileLogger` and `FileRotationLogger` have been changed.

Thanks.

**Comment by sushichop** [comment]
I'm going to close this issue as I haven't heard from you in a while unfortunately.
This issue has already been fixed.

Try to use the latest version [Puppy 0.5.0](https://github.com/sushichop/Puppy/releases/tag/0.5.0). And Windows is now supported.

Thanks.
