### ISSUE TITLE
Problem with module compilation in swift

### ISSUE THREAD

**Issue by klukaspl** [sushichop/Puppy#65]
Hi,
I have problem after adding the swift package with Puppy to my application. Could anyone please tell me what I am doing wrong?
I am trying on macOS on Intel machine with XCode Version 13.4 (13F17a).

Undefined symbols for architecture x86_64:
  "type metadata accessor for Puppy.FileLogger", referenced from:
      Action.metoda() -> () in Logger.o
  "Puppy.FileLogger.__allocating_init(_: Swift.String, fileURL: Foundation.URL, filePermission: Swift.String, flushMode: Puppy.FileLogger.FlushMode) throws -> Puppy.FileLogger", referenced from:
      Action.metoda() -> () in Logger.o
  "Puppy.Puppy.__allocating_init() -> Puppy.Puppy", referenced from:
      one-time initialization function for log in Logger.o
  "type metadata accessor for Puppy.Puppy", referenced from:
      one-time initialization function for log in Logger.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by sushichop** [comment]
I confirmed that I can build the application project by simply adding `Puppy` version 0.5.1 from the Xcode menu.

And `Puppy` does not use `Action.metoda()`. I'm not sure, but I don't think this issue is directly related to `Puppy`.

**Comment by sushichop** [comment]
Can you share your `Package.swift`?
It may help us to solve this issue.

**Comment by sushichop** [comment]
I'm going to close this issue as I haven't heard from you in a while unfortunately. 
If you still have the issue or any question, feel free to reopen this.

Thanks.
