### ISSUE TITLE
Typo in README example

### ISSUE THREAD

**Issue by neilhamilton** [sushichop/Puppy#67]
```
class SampleFileRotationDelegate: FileRotationLoggerDeletate {
```

should be updated to:
```
class SampleFileRotationDelegate: FileRotationLoggerDelegate {
```

**Comment by sushichop** [comment]
@neilhamilton 
Thanks! I fixed typo in README.
https://github.com/sushichop/Puppy/commit/4d01fb2579ddf7a4df4191c893871517a6590ed7

**Comment by sushichop** [comment]
I'll now close this issue.
Thanks.
