### ISSUE TITLE
using dateFormatter is really inefficient 

### ISSUE THREAD

**Issue by nagypeterjob** [sushichop/Puppy#80]
Hey @sushichop  👋🏻 

First of all, thank you for working on Puppy! Puppy is my go-to Swift logging lib, I really appreciate the amount of work you are investing in it.

Now to the issue. There is a section in the README, which shows how to use `LogFormattable`. In this example, the **date** value is returned by  the `dateFormatter` function:
```swift
struct LogFormatter: LogFormattable {
    func formatMessage(_ level: LogLevel, message: String, tag: String, function: String,
                       file: String, line: UInt, swiftLogInfo: [String : String],
                       label: String, date: Date, threadID: UInt64) -> String {
        let date = dateFormatter(date)
        let fileName = fileName(file)
        let moduleName = moduleName(file)
        return "\(date) \(threadID) [\(level.emoji) \(level)] \(swiftLogInfo) \(moduleName)/\(fileName)#L.\(line) \(function) \(message)".colorize(level.color)
    }
}
```
`dateFormatter` looks like this:
```swift
@Sendable
public func dateFormatter(_ date: Date, locale: String = "en_US_POSIX", dateFormat: String = "yyyy-MM-dd'T'HH:mm:ss.SSSZZZZZ", timeZone: String = "") -> String {
    let dateFormatter = DateFormatter()
    dateFormatter.locale = Locale(identifier: locale)
    dateFormatter.dateFormat = dateFormat
    dateFormatter.timeZone = TimeZone(identifier: timeZone)
    return dateFormatter.string(from: date)
}
```

You see, calling the `DateFormatter()` constructor is a [really expensive operation](https://sarunw.com/posts/how-expensive-is-dateformatter/), and in this case, it is being called on each log event. Performance can be greatly improved by pre-initialising  the `DateFormatter()` object, and injecting it into the `formatMessage` function.

There are multiple ways to address this, would you like me to create a PR?

**Comment by sushichop** [comment]
@nagypeterjob 
Thanks for sharing your idea!
Yes. Every PR is always welcome🙂

**Comment by nagypeterjob** [comment]
I have pushed a PR, let me know what you think @sushichop

**Comment by sushichop** [comment]
@nagypeterjob 
Thanks for your PR. I have merged your PR.

It makes sense not to call `DateFormatter()` on each log event. 
In addition, it's cool that the performance measurement has been added in tests👍
